//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBudgeting
{
    using System;
    using System.Collections.Generic;
    
    public partial class overviewTable
    {
        public string budgetItem { get; set; }
        public decimal amtBudgeted { get; set; }
        public decimal amtRemaining { get; set; }
    }
}
